all:
	pdflatex seminar.tex
	bibtex seminar
	pdflatex seminar.tex
	bibtex seminar
	pdflatex seminar.tex
	bibtex seminar

challenge:
	pdflatex challenge.tex
	bibtex challenge
	pdflatex challenge.tex
	bibtex challenge
	pdflatex challenge.tex
	bibtex challenge

clean:
	rm seminar.aux seminar.log seminar.blg
	rm challenge.aux challenge.log challenge.blg
