all:
	pdflatex seminar.tex
	bibtex seminar
	pdflatex seminar.tex
	bibtex seminar
	pdflatex seminar.tex
	bibtex seminar

challenge:
	pdflatex challenge.tex
	bibtex challenge
	pdflatex challenge.tex
	bibtex challenge
	pdflatex challenge.tex
	bibtex challenge

clean:
	rm *.bbl *.aux *.log *.blg
